/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _BISCUITOS_X86_KVM_X86_H
#define _BISCUITOS_X86_KVM_X86_H

#define KVM_DEFAULT_PLE_GAP             128
#define KVM_VMX_DEFAULT_PLE_WINDOW      4096
#define KVM_DEFAULT_PLE_WINDOW_GROW     2
#define KVM_DEFAULT_PLE_WINDOW_SHRINK   0
#define KVM_VMX_DEFAULT_PLE_WINDOW_MAX  UINT_MAX
#define KVM_SVM_DEFAULT_PLE_WINDOW_MAX  USHRT_MAX
#define KVM_SVM_DEFAULT_PLE_WINDOW      3000

#endif
