obj-$(CONFIG_BISCUITOS_PROC_FS)		+= proc.o

proc-$(CONFIG_BISCUITOS_PROC_FS)	:= root.o
proc-$(CONFIG_BISCUITOS_PROC_FS)	+= inode.o
proc-$(CONFIG_BISCUITOS_PROC_FS)	+= generic.o
proc-$(CONFIG_BISCUITOS_PROC_FS)	+= base.o
proc-$(CONFIG_BISCUITOS_PROC_FS)	+= fd.o
proc-$(CONFIG_BISCUITOS_PROC_FS)	+= self.o
proc-$(CONFIG_BISCUITOS_PROC_FS)	+= thread_self.o
proc-$(CONFIG_BISCUITOS_PROC_FS)	+= util.o
proc-$(CONFIG_BISCUITOS_PROC_FS)	+= proc_sysctl.o
proc-$(CONFIG_BISCUITOS_PROC_FS)	+= sysctl.o
